//! Synth patches: leads, pads, keys, plucks, basses and an effect.

use super::{FactoryPreset, preset};

pub(super) fn synth() -> Vec<FactoryPreset> {
    use crate::devices::synth::id::*;
    const SAW: f64 = 0.0;
    const SQUARE: f64 = 1.0;
    const TRIANGLE: f64 = 2.0;
    const SINE: f64 = 3.0;
    const LP12: f64 = 0.0;
    const LP24: f64 = 1.0;
    const BAND: f64 = 2.0;
    const OWN: f64 = 1.0;
    const MONO: f64 = 1.0;
    const LEGATO: f64 = 2.0;
    const LFO_TRIANGLE: f64 = 1.0;
    const EIGHTH: f64 = 8.0;
    vec![
        // Leads.
        preset(
            "Fat Saw Lead",
            &[
                (VOLUME, -9.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SAW),
                (DETUNE, 12.0),
                (UNISON, 3.0),
                (UNISON_SPREAD, 12.0),
                (WIDTH, 0.5),
                (FILTER_TYPE, LP24),
                (CUTOFF, 1_800.0),
                (RESONANCE, 0.3),
                (ENV_AMOUNT, 0.35),
                (FILTER_ENV, OWN),
                (F_ATTACK, 2.0),
                (F_DECAY, 400.0),
                (F_SUSTAIN, 0.5),
                (F_RELEASE, 300.0),
                (ATTACK, 3.0),
                (DECAY, 200.0),
                (SUSTAIN, 0.9),
                (RELEASE, 250.0),
                (VOICE_MODE, LEGATO),
                (GLIDE, 60.0),
                (DRIVE, 0.2),
                (KEY_TRACK, 0.5),
                (VELOCITY_CUTOFF, 0.5),
            ],
        ),
        preset(
            "Supersaw Stack",
            &[
                (VOLUME, -12.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SAW),
                (DETUNE, 15.0),
                (UNISON, 7.0),
                (UNISON_SPREAD, 35.0),
                (WIDTH, 1.0),
                (FILTER_TYPE, LP12),
                (CUTOFF, 6_000.0),
                (RESONANCE, 0.1),
                (ENV_AMOUNT, 0.15),
                (FILTER_ENV, OWN),
                (F_ATTACK, 5.0),
                (F_DECAY, 600.0),
                (F_SUSTAIN, 0.7),
                (F_RELEASE, 500.0),
                (ATTACK, 10.0),
                (DECAY, 500.0),
                (SUSTAIN, 0.85),
                (RELEASE, 600.0),
                (KEY_TRACK, 0.4),
                (VELOCITY_CUTOFF, 0.4),
            ],
        ),
        // A square and a quick vibrato, monophonic.
        preset(
            "Chip Lead",
            &[
                (VOLUME, -12.0),
                (OSC1_WAVE, SQUARE),
                (OSC1_PW, 0.5),
                (OSC2_LEVEL, 0.0),
                (DETUNE, 0.0),
                (CUTOFF, 14_000.0),
                (RESONANCE, 0.0),
                (ENV_AMOUNT, 0.0),
                (ATTACK, 1.0),
                (DECAY, 100.0),
                (SUSTAIN, 1.0),
                (RELEASE, 60.0),
                (VOICE_MODE, MONO),
                (LFO_RATE, 6.0),
                (LFO_PITCH, 25.0),
                (VELOCITY_AMP, 0.3),
                (VELOCITY_CUTOFF, 0.0),
                (WIDTH, 0.0),
            ],
        ),
        // Pads and strings.
        preset(
            "Warm Pad",
            &[
                (VOLUME, -10.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SAW),
                (DETUNE, 10.0),
                (UNISON, 3.0),
                (UNISON_SPREAD, 12.0),
                (WIDTH, 1.0),
                (FILTER_TYPE, LP24),
                (CUTOFF, 900.0),
                (RESONANCE, 0.15),
                (ENV_AMOUNT, 0.25),
                (FILTER_ENV, OWN),
                (F_ATTACK, 1_200.0),
                (F_DECAY, 2_000.0),
                (F_SUSTAIN, 0.6),
                (F_RELEASE, 1_500.0),
                (ATTACK, 800.0),
                (DECAY, 1_500.0),
                (SUSTAIN, 0.85),
                (RELEASE, 1_800.0),
                (LFO_SHAPE, LFO_TRIANGLE),
                (LFO_RATE, 0.25),
                (LFO_CUTOFF, 0.3),
                (KEY_TRACK, 0.5),
                (VELOCITY_CUTOFF, 0.3),
                (VELOCITY_AMP, 0.5),
            ],
        ),
        // Pulse width swept by the LFO: the slow shimmer of string machines.
        preset(
            "PWM Pad",
            &[
                (VOLUME, -11.0),
                (OSC1_WAVE, SQUARE),
                (OSC2_WAVE, SQUARE),
                (OSC1_PW, 0.5),
                (OSC2_LEVEL, 0.7),
                (DETUNE, 6.0),
                (UNISON, 2.0),
                (UNISON_SPREAD, 8.0),
                (WIDTH, 1.0),
                (FILTER_TYPE, LP12),
                (CUTOFF, 2_200.0),
                (RESONANCE, 0.1),
                (ENV_AMOUNT, 0.2),
                (ATTACK, 300.0),
                (DECAY, 1_000.0),
                (SUSTAIN, 0.9),
                (RELEASE, 900.0),
                (LFO_SHAPE, LFO_TRIANGLE),
                (LFO_RATE, 0.4),
                (LFO_PW, 0.35),
                (VELOCITY_AMP, 0.5),
            ],
        ),
        preset(
            "Soft Strings",
            &[
                (VOLUME, -12.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SAW),
                (OSC2_OCTAVE, 1.0),
                (OSC2_LEVEL, 0.4),
                (DETUNE, 14.0),
                (UNISON, 5.0),
                (UNISON_SPREAD, 25.0),
                (WIDTH, 1.0),
                (FILTER_TYPE, LP12),
                (CUTOFF, 3_200.0),
                (RESONANCE, 0.05),
                (ENV_AMOUNT, 0.1),
                (FILTER_ENV, OWN),
                (F_ATTACK, 400.0),
                (F_SUSTAIN, 0.8),
                (ATTACK, 350.0),
                (DECAY, 800.0),
                (SUSTAIN, 0.9),
                (RELEASE, 900.0),
                (LFO_RATE, 5.0),
                (LFO_PITCH, 6.0),
                (KEY_TRACK, 0.5),
                (VELOCITY_AMP, 0.6),
            ],
        ),
        // The filter opens a little after the note, as a player's lips do.
        preset(
            "Analog Brass",
            &[
                (VOLUME, -9.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SAW),
                (DETUNE, 8.0),
                (UNISON, 2.0),
                (UNISON_SPREAD, 8.0),
                (WIDTH, 0.6),
                (FILTER_TYPE, LP24),
                (CUTOFF, 700.0),
                (RESONANCE, 0.2),
                (ENV_AMOUNT, 0.55),
                (FILTER_ENV, OWN),
                (F_ATTACK, 60.0),
                (F_DECAY, 500.0),
                (F_SUSTAIN, 0.45),
                (F_RELEASE, 300.0),
                (ATTACK, 30.0),
                (DECAY, 300.0),
                (SUSTAIN, 0.85),
                (RELEASE, 250.0),
                (KEY_TRACK, 0.5),
                (VELOCITY_CUTOFF, 0.8),
            ],
        ),
        // Keys, plucks and bells.
        preset(
            "Pluck",
            &[
                (VOLUME, -9.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SQUARE),
                (OSC2_LEVEL, 0.6),
                (DETUNE, 6.0),
                (UNISON, 2.0),
                (UNISON_SPREAD, 10.0),
                (WIDTH, 0.8),
                (FILTER_TYPE, LP12),
                (CUTOFF, 400.0),
                (RESONANCE, 0.3),
                (ENV_AMOUNT, 0.7),
                (FILTER_ENV, OWN),
                (F_ATTACK, 1.0),
                (F_DECAY, 220.0),
                (F_SUSTAIN, 0.0),
                (F_RELEASE, 200.0),
                (ATTACK, 1.0),
                (DECAY, 600.0),
                (SUSTAIN, 0.0),
                (RELEASE, 400.0),
                (KEY_TRACK, 0.6),
                (VELOCITY_CUTOFF, 0.8),
            ],
        ),
        // Two sines a tenth apart: a bell's minor-third partials.
        preset(
            "Glass Bells",
            &[
                (VOLUME, -8.0),
                (OSC1_WAVE, SINE),
                (OSC2_WAVE, SINE),
                (OSC2_OCTAVE, 1.0),
                (OSC2_SEMI, 3.0),
                (OSC2_LEVEL, 0.5),
                (DETUNE, 2.0),
                (WIDTH, 0.8),
                (CUTOFF, 14_000.0),
                (RESONANCE, 0.0),
                (ENV_AMOUNT, 0.0),
                (ATTACK, 1.0),
                (DECAY, 1_800.0),
                (SUSTAIN, 0.0),
                (RELEASE, 1_500.0),
                (VELOCITY_AMP, 0.9),
            ],
        ),
        preset(
            "Tremolo Keys",
            &[
                (VOLUME, -8.0),
                (OSC1_WAVE, TRIANGLE),
                (OSC2_WAVE, SINE),
                (OSC2_OCTAVE, 1.0),
                (OSC2_LEVEL, 0.3),
                (DETUNE, 1.0),
                (WIDTH, 0.7),
                (FILTER_TYPE, LP12),
                (CUTOFF, 2_500.0),
                (RESONANCE, 0.0),
                (ENV_AMOUNT, 0.3),
                (FILTER_ENV, OWN),
                (F_ATTACK, 1.0),
                (F_DECAY, 800.0),
                (F_SUSTAIN, 0.2),
                (F_RELEASE, 400.0),
                (ATTACK, 2.0),
                (DECAY, 1_500.0),
                (SUSTAIN, 0.3),
                (RELEASE, 500.0),
                (LFO_RATE, 4.5),
                (LFO_AMP, 0.3),
                (KEY_TRACK, 0.5),
                (VELOCITY_CUTOFF, 0.9),
            ],
        ),
        // Basses.
        preset(
            "Sub Bass",
            &[
                (VOLUME, -6.0),
                (OSC1_WAVE, SINE),
                (OSC2_WAVE, TRIANGLE),
                (OSC2_LEVEL, 0.25),
                (DETUNE, 0.0),
                (WIDTH, 0.0),
                (CUTOFF, 1_200.0),
                (RESONANCE, 0.0),
                (ENV_AMOUNT, 0.0),
                (ATTACK, 3.0),
                (DECAY, 300.0),
                (SUSTAIN, 1.0),
                (RELEASE, 80.0),
                (VOICE_MODE, MONO),
                (DRIVE, 0.15),
                (VELOCITY_AMP, 0.4),
                (VELOCITY_CUTOFF, 0.0),
            ],
        ),
        // One saw, a resonant 24 dB filter snapping shut, slides between
        // tied notes.
        preset(
            "Acid Bass",
            &[
                (VOLUME, -8.0),
                (OSC1_WAVE, SAW),
                (OSC2_LEVEL, 0.0),
                (DETUNE, 0.0),
                (WIDTH, 0.0),
                (FILTER_TYPE, LP24),
                (CUTOFF, 300.0),
                (RESONANCE, 0.85),
                (ENV_AMOUNT, 0.6),
                (FILTER_ENV, OWN),
                (F_ATTACK, 1.0),
                (F_DECAY, 180.0),
                (F_SUSTAIN, 0.0),
                (F_RELEASE, 120.0),
                (ATTACK, 1.0),
                (DECAY, 250.0),
                (SUSTAIN, 0.7),
                (RELEASE, 60.0),
                (VOICE_MODE, LEGATO),
                (GLIDE, 40.0),
                (DRIVE, 0.5),
                (VELOCITY_CUTOFF, 1.0),
            ],
        ),
        preset(
            "Fat Analog Bass",
            &[
                (VOLUME, -7.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SQUARE),
                (OSC2_OCTAVE, -1.0),
                (OSC2_LEVEL, 0.7),
                (DETUNE, 4.0),
                (SUB, 0.3),
                (WIDTH, 0.2),
                (FILTER_TYPE, LP24),
                (CUTOFF, 500.0),
                (RESONANCE, 0.3),
                (ENV_AMOUNT, 0.4),
                (FILTER_ENV, OWN),
                (F_ATTACK, 1.0),
                (F_DECAY, 350.0),
                (F_SUSTAIN, 0.2),
                (F_RELEASE, 200.0),
                (ATTACK, 1.0),
                (DECAY, 400.0),
                (SUSTAIN, 0.8),
                (RELEASE, 100.0),
                (VOICE_MODE, MONO),
                (DRIVE, 0.3),
                (KEY_TRACK, 0.3),
            ],
        ),
        // The filter swept in eighths of the song's tempo.
        preset(
            "Wobble Bass",
            &[
                (VOLUME, -9.0),
                (OSC1_WAVE, SAW),
                (OSC2_WAVE, SQUARE),
                (OSC2_OCTAVE, -1.0),
                (OSC2_LEVEL, 0.8),
                (DETUNE, 8.0),
                (SUB, 0.4),
                (WIDTH, 0.3),
                (FILTER_TYPE, LP24),
                (CUTOFF, 250.0),
                (RESONANCE, 0.5),
                (ENV_AMOUNT, 0.0),
                (ATTACK, 2.0),
                (SUSTAIN, 1.0),
                (RELEASE, 80.0),
                (LFO_SYNC, 1.0),
                (LFO_DIVISION, EIGHTH),
                (LFO_CUTOFF, 3.0),
                (VOICE_MODE, MONO),
                (DRIVE, 0.6),
            ],
        ),
        // Effect: filtered noise swelling over four seconds.
        preset(
            "Noise Riser",
            &[
                (VOLUME, -6.0),
                (OSC1_LEVEL, 0.0),
                (OSC2_LEVEL, 0.0),
                (NOISE, 1.0),
                (FILTER_TYPE, BAND),
                (CUTOFF, 300.0),
                (RESONANCE, 0.6),
                (ENV_AMOUNT, 0.7),
                (FILTER_ENV, OWN),
                (F_ATTACK, 4_000.0),
                (F_DECAY, 4_000.0),
                (F_SUSTAIN, 1.0),
                (F_RELEASE, 2_000.0),
                (ATTACK, 4_000.0),
                (DECAY, 1_000.0),
                (SUSTAIN, 1.0),
                (RELEASE, 2_000.0),
                (KEY_TRACK, 0.0),
                (VELOCITY_CUTOFF, 0.0),
            ],
        ),
    ]
}
