[package]
name = "faderframe-audio-jack"
description = "JACK audio backend (works with JACK2 and pipewire-jack)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
faderframe-audio.workspace = true
tracing.workspace = true
rtrb.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
jack.workspace = true
