#!/usr/bin/env python3
"""Bake the lead sheet engraver's assets into Rust.

    uv run --no-project --with fonttools scripts/notation_assets.py <bravura dir> <afm dir>

<bravura dir> holds Bravura.otf, Bravura.json (its SMuFL metadata) and
OFL.txt from github.com/steinbergmedia/bravura (redist/); <afm dir> the
Adobe Core 14 AFM files Helvetica, Helvetica-Bold, Times-Roman,
Times-Bold, Times-Italic and their MustRead.html (from pdfkit's
lib/font/data). Writes crates/faderframe-leadsheet/src/assets.rs (the
glyph outlines the engraver draws, in staff spaces with y up, its
engraving defaults and the five fonts' advance widths for the PDF's
WinAnsi text) and the licences next to it in data/.
"""

import json
import pathlib
import shutil
import sys

from fontTools.agl import UV2AGL
from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
CRATE = ROOT / "crates" / "faderframe-leadsheet"

# SMuFL names the engraver uses, with their code points.
GLYPHS = {
    "gClef": 0xE050,
    "gClef8vb": 0xE052,
    "fClef": 0xE062,
    "timeSig0": 0xE080,
    "timeSig1": 0xE081,
    "timeSig2": 0xE082,
    "timeSig3": 0xE083,
    "timeSig4": 0xE084,
    "timeSig5": 0xE085,
    "timeSig6": 0xE086,
    "timeSig7": 0xE087,
    "timeSig8": 0xE088,
    "timeSig9": 0xE089,
    "timeSigCommon": 0xE08A,
    "noteheadWhole": 0xE0A2,
    "noteheadHalf": 0xE0A3,
    "noteheadBlack": 0xE0A4,
    "augmentationDot": 0xE1E7,
    "flag8thUp": 0xE240,
    "flag8thDown": 0xE241,
    "flag16thUp": 0xE242,
    "flag16thDown": 0xE243,
    "accidentalFlat": 0xE260,
    "accidentalNatural": 0xE261,
    "accidentalSharp": 0xE262,
    "accidentalDoubleSharp": 0xE263,
    "accidentalDoubleFlat": 0xE264,
    "restWhole": 0xE4E3,
    "restHalf": 0xE4E4,
    "restQuarter": 0xE4E5,
    "rest8th": 0xE4E6,
    "rest16th": 0xE4E7,
    "tuplet3": 0xE883,
    "metNoteQuarterUp": 0xECA5,
}

DEFAULTS = [
    "staffLineThickness",
    "stemThickness",
    "beamThickness",
    "beamSpacing",
    "legerLineThickness",
    "legerLineExtension",
    "thinBarlineThickness",
    "thickBarlineThickness",
    "thinThickBarlineSeparation",
    "tieEndpointThickness",
    "tieMidpointThickness",
    "lyricLineThickness",
    "tupletBracketThickness",
]

FONTS = ["Helvetica", "Helvetica-Bold", "Times-Roman", "Times-Bold", "Times-Italic"]


class Segments(BasePen):
    """Moves, lines and cubics in staff spaces (250 font units)."""

    def __init__(self, glyphs):
        super().__init__(glyphs)
        self.out = []

    def s(self, p):
        return (round(p[0] / 250.0, 4), round(p[1] / 250.0, 4))

    def _moveTo(self, p):
        self.out.append(("M", self.s(p)))

    def _lineTo(self, p):
        self.out.append(("L", self.s(p)))

    def _curveToOne(self, a, b, c):
        self.out.append(("C", self.s(a) + self.s(b) + self.s(c)))

    def _closePath(self):
        self.out.append(("Z", ()))

    def _endPath(self):
        pass


def f(v):
    t = f"{v:.4f}".rstrip("0").rstrip(".")
    if t in ("-0", ""):
        t = "0"
    return t + ("" if "." in t else ".0")


def seg(s):
    op, args = s
    if op == "Z":
        return "Seg::Z"
    return f"Seg::{op}({', '.join(f(a) for a in args)})"


def afm_widths(path):
    widths = {}
    for line in path.read_text(encoding="latin-1").splitlines():
        if line.startswith("C "):
            parts = [p.strip() for p in line.split(";")]
            wx = name = None
            for p in parts:
                if p.startswith("WX "):
                    wx = int(float(p[3:]))
                elif p.startswith("N "):
                    name = p[2:].strip()
            if name is not None and wx is not None:
                widths[name] = wx
    row = []
    for code in range(32, 256):
        try:
            ch = bytes([code]).decode("cp1252")
        except UnicodeDecodeError:
            row.append(widths.get("space", 250))
            continue
        name = UV2AGL.get(ord(ch), "space")
        row.append(widths.get(name, widths.get("space", 250)))
    return row


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    bravura = pathlib.Path(sys.argv[1])
    afm = pathlib.Path(sys.argv[2])
    font = TTFont(bravura / "Bravura.otf")
    meta = json.loads((bravura / "Bravura.json").read_text(encoding="utf-8-sig"))
    cmap = font.getBestCmap()
    glyph_set = font.getGlyphSet()
    hmtx = font["hmtx"]
    out = []
    out.append("// Generated by scripts/notation_assets.py — do not edit.\n")
    out.append("//\n")
    out.append("// Glyph outlines derived from the Bravura font, copyright © 2015\n")
    out.append("// Steinberg Media Technologies GmbH, under the SIL Open Font License\n")
    out.append("// 1.1 (data/OFL-Bravura.txt). Text font widths from Adobe's Core 14\n")
    out.append("// AFM files, copyright © 1985–1997 Adobe Systems Incorporated\n")
    out.append("// (data/AFM-NOTICE.txt; only the advance widths taken, for WinAnsi).\n\n")
    out.append("use crate::glyph::{Glyph, Seg};\n\n")
    defaults = meta["engravingDefaults"]
    out.append("/// Bravura's engraving defaults (staff spaces).\n")
    out.append("pub mod engraving {\n")
    for k in DEFAULTS:
        snake = "".join("_" + c.lower() if c.isupper() else c for c in k).upper()
        out.append(f"    pub const {snake}: f32 = {f(defaults[k])};\n")
    out.append("}\n\n")
    anchors = meta["glyphsWithAnchors"]
    out.append("pub static GLYPHS: [Glyph; %d] = [\n" % len(GLYPHS))
    for name, cp in GLYPHS.items():
        gname = cmap[cp]
        pen = Segments(glyph_set)
        glyph_set[gname].draw(pen)
        bbox = meta["glyphBBoxes"][name]
        sw, ne = bbox["bBoxSW"], bbox["bBoxNE"]
        adv = hmtx[gname][0] / 250.0
        a = anchors.get(name, {})
        up = a.get("stemUpSE", [0.0, 0.0])
        down = a.get("stemDownNW", [0.0, 0.0])
        out.append("    Glyph {\n")
        out.append(f"        name: \"{name}\",\n")
        out.append(f"        code: 0x{cp:04X},\n")
        out.append(f"        advance: {f(adv)},\n")
        out.append(f"        bbox: [{f(sw[0])}, {f(sw[1])}, {f(ne[0])}, {f(ne[1])}],\n")
        out.append(f"        stem_up: [{f(up[0])}, {f(up[1])}],\n")
        out.append(f"        stem_down: [{f(down[0])}, {f(down[1])}],\n")
        out.append("        path: &[\n")
        for s in pen.out:
            out.append(f"            {seg(s)},\n")
        out.append("        ],\n")
        out.append("    },\n")
    out.append("];\n\n")
    out.append("/// The PDF's text fonts, in this order.\n")
    out.append("pub const FONT_NAMES: [&str; %d] = [%s];\n\n" % (len(FONTS), ", ".join(f'"{n}"' for n in FONTS)))
    out.append("/// Advance widths (1/1000 em) of WinAnsi codes 32…255, per font.\n")
    out.append("pub static WIDTHS: [[u16; 224]; %d] = [\n" % len(FONTS))
    for name in FONTS:
        row = afm_widths(afm / f"{name}.afm")
        out.append("    [\n")
        for i in range(0, len(row), 16):
            out.append("        " + ", ".join(str(w) for w in row[i : i + 16]) + ",\n")
        out.append("    ],\n")
    out.append("];\n")
    (CRATE / "src").mkdir(parents=True, exist_ok=True)
    (CRATE / "src" / "assets.rs").write_text("".join(out), encoding="utf-8")
    data = CRATE / "data"
    data.mkdir(parents=True, exist_ok=True)
    shutil.copy(bravura / "OFL.txt", data / "OFL-Bravura.txt")
    notice = (afm / "MustRead.html").read_text(encoding="latin-1")
    import re

    text = re.sub(r"<[^>]+>", "", notice)
    text = "\n".join(l.strip() for l in text.splitlines() if l.strip())
    copyright = []
    for name in FONTS:
        for line in (afm / f"{name}.afm").read_text(encoding="latin-1").splitlines():
            if line.startswith("Comment Copyright") or line.startswith("Notice "):
                copyright.append(f"{name}: {line.split(' ', 1)[1]}")
    (data / "AFM-NOTICE.txt").write_text(
        "The advance widths in src/assets.rs (WIDTHS) were taken from Adobe's\n"
        "Core 14 AFM files for Helvetica, Helvetica-Bold, Times-Roman,\n"
        "Times-Bold and Times-Italic (modified: only the widths of the\n"
        "WinAnsi characters kept, by scripts/notation_assets.py).\n\n"
        + "\n".join(copyright)
        + "\n\n"
        + text
        + "\n",
        encoding="utf-8",
    )
    print(f"{len(GLYPHS)} glyphs, {len(FONTS)} fonts")


if __name__ == "__main__":
    main()
