#!/usr/bin/env python3
"""Generate THIRD_PARTY_LICENSES.md from `cargo metadata`.

Lists every crate FaderFrame links into its binaries (normal + build
dependencies reachable from the workspace members; dev-dependencies are
excluded) with its SPDX license expression, and reproduces each distinct
license text once together with the crates it applies to. System libraries
that are linked dynamically (and therefore not redistributed by this
repository) are listed separately, and so are C/C++ libraries vendored
into a crate and compiled into the binaries.

Usage:
    python3 scripts/third_party_licenses.py           # (re)write the file
    python3 scripts/third_party_licenses.py --check   # fail if out of date

Standard library only; no third-party Python packages required.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.md"
LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|notice)", re.IGNORECASE)

SYSTEM_LIBRARIES = [
    ("GTK 4", "LGPL-2.1-or-later", "https://gitlab.gnome.org/GNOME/gtk", "GUI toolkit (dynamically linked)"),
    ("GLib / GIO / GObject", "LGPL-2.1-or-later", "https://gitlab.gnome.org/GNOME/glib", "dynamically linked"),
    ("Pango", "LGPL-2.0-or-later", "https://gitlab.gnome.org/GNOME/pango", "text layout (dynamically linked)"),
    ("Cairo", "LGPL-2.1-only OR MPL-1.1", "https://gitlab.freedesktop.org/cairo/cairo", "used by GTK (dynamically linked)"),
    ("Graphene", "MIT", "https://github.com/ebassi/graphene", "geometry types (dynamically linked)"),
    ("HarfBuzz", "MIT-like (Old MIT)", "https://github.com/harfbuzz/harfbuzz", "text shaping via Pango"),
    ("libjack (JACK2)", "LGPL-2.1-or-later", "https://github.com/jackaudio/jack2", "loaded at runtime with dlopen"),
    ("pipewire-jack", "MIT", "https://gitlab.freedesktop.org/pipewire/pipewire", "alternative libjack provider, loaded at runtime"),
]


# (name, version, license, source, licence file relative to the repository)
VENDORED = [
    (
        "Signalsmith Stretch",
        "1.3.1",
        "MIT",
        "https://github.com/Signalsmith-Audio/signalsmith-stretch",
        "crates/faderframe-stretch/vendor/signalsmith-stretch/LICENSE.txt",
    ),
    (
        "Signalsmith Linear",
        "(with Stretch 1.3.1)",
        "MIT",
        "https://github.com/Signalsmith-Audio/linear",
        "crates/faderframe-stretch/vendor/signalsmith-linear/LICENSE.txt",
    ),
]


def cargo_metadata() -> dict:
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked", "--filter-platform", "x86_64-unknown-linux-gnu"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return json.loads(out)


def runtime_packages(meta: dict) -> list[dict]:
    members = set(meta["workspace_members"])
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    seen: set[str] = set()
    stack = list(members)
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            kinds = {k["kind"] for k in dep["dep_kinds"]}
            if kinds & {None, "build"}:
                stack.append(dep["pkg"])
    pkgs = [p for p in meta["packages"] if p["id"] in seen and p["id"] not in members]
    return sorted(pkgs, key=lambda p: (p["name"], p["version"]))


def license_texts(pkg: dict) -> list[tuple[str, str]]:
    folder = Path(pkg["manifest_path"]).parent
    texts = []
    for f in sorted(folder.iterdir()):
        if f.is_file() and LICENSE_FILE.match(f.name):
            try:
                texts.append((f.name, f.read_text(encoding="utf-8", errors="replace").strip()))
            except OSError:
                pass
    return texts


def normalise(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def render(meta: dict) -> str:
    pkgs = runtime_packages(meta)
    groups: dict[str, dict] = {}
    missing: list[str] = []
    for p in pkgs:
        label = f"{p['name']} {p['version']}"
        files = license_texts(p)
        if not files:
            missing.append(label)
        for name, text in files:
            key = hashlib.sha256(normalise(text).encode()).hexdigest()
            g = groups.setdefault(key, {"name": name, "text": text, "crates": []})
            g["crates"].append(label)

    lines = [
        "# Third-party licenses",
        "",
        "<!-- Generated by scripts/third_party_licenses.py — do not edit by hand. -->",
        "",
        "FaderFrame itself is licensed under the MIT license (see `LICENSE`).",
        "This file lists the third-party components that end up in FaderFrame",
        "binaries, followed by the full text of every distinct license.",
        "",
        "## System libraries (dynamically linked, not bundled)",
        "",
        "| Library | License | Source | Notes |",
        "|---|---|---|---|",
    ]
    for name, lic, url, note in SYSTEM_LIBRARIES:
        lines.append(f"| {name} | {lic} | {url} | {note} |")
    lines += [
        "",
        "These libraries are provided by the operating system and loaded at run",
        "time; binary distributions that bundle them (e.g. Windows or macOS",
        "installers) must ship their license texts and comply with the LGPL's",
        "relinking provisions.",
        "",
        f"## Rust crates ({len(pkgs)})",
        "",
        "Crates under the MPL-2.0 (the Symphonia audio decoders) are file-level",
        "copyleft: FaderFrame uses them unmodified from crates.io, where their",
        "source is available; modified versions of those files would have to be",
        "published under the MPL-2.0 as well.",
        "",
        "| Crate | Version | License | Repository |",
        "|---|---|---|---|",
    ]
    for p in pkgs:
        repo = p.get("repository") or ""
        lic = (p.get("license") or "see license file").replace("|", "\\|")
        lines.append(f"| {p['name']} | {p['version']} | {lic} | {repo} |")
    lines += [
        "",
        f"## Vendored C/C++ libraries ({len(VENDORED)}, compiled in)",
        "",
        "| Library | Version | License | Source |",
        "|---|---|---|---|",
    ]
    for name, version, lic, url, path in VENDORED:
        lines.append(f"| {name} | {version} | {lic} | {url} |")
        text = (ROOT / path).read_text(encoding="utf-8").strip()
        key = hashlib.sha256(normalise(text).encode()).hexdigest()
        g = groups.setdefault(key, {"name": Path(path).name, "text": text, "crates": []})
        g["crates"].append(f"{name} (vendored)")
    if missing:
        lines += [
            "",
            "Crates without a license file in their published package (license per",
            "their SPDX expression above; texts at https://spdx.org/licenses/):",
            "",
            ", ".join(missing),
        ]
    lines += ["", "## License texts", ""]
    for g in sorted(groups.values(), key=lambda g: (-len(g["crates"]), g["crates"][0])):
        crates = ", ".join(sorted(set(g["crates"])))
        lines += [
            f"### {g['name']}",
            "",
            f"Applies to: {crates}",
            "",
            "```text",
            g["text"].replace("```", "'''"),
            "```",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    text = render(cargo_metadata())
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("THIRD_PARTY_LICENSES.md is out of date; run scripts/third_party_licenses.py", file=sys.stderr)
            return 1
        print("THIRD_PARTY_LICENSES.md is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
